// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent that suggests taglines for a portfolio website.
 *
 * - suggestTaglines - A function that suggests taglines.
 * - SuggestTaglinesInput - The input type for the suggestTaglines function.
 * - SuggestTaglinesOutput - The return type for the suggestTaglines function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestTaglinesInputSchema = z.object({
  keywords: z.string().describe('Keywords describing the portfolio owner and their work.'),
});
export type SuggestTaglinesInput = z.infer<typeof SuggestTaglinesInputSchema>;

const SuggestTaglinesOutputSchema = z.object({
  taglines: z.array(z.string()).describe('An array of suggested taglines.'),
});
export type SuggestTaglinesOutput = z.infer<typeof SuggestTaglinesOutputSchema>;

export async function suggestTaglines(input: SuggestTaglinesInput): Promise<SuggestTaglinesOutput> {
  return suggestTaglinesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestTaglinesPrompt',
  input: {schema: SuggestTaglinesInputSchema},
  output: {schema: SuggestTaglinesOutputSchema},
  prompt: `You are a marketing expert specializing in creating taglines for portfolios.

  Based on the keywords provided, generate 3 professional and engaging taglines for a portfolio website.

  Keywords: {{{keywords}}}
  `,
});

const suggestTaglinesFlow = ai.defineFlow(
  {
    name: 'suggestTaglinesFlow',
    inputSchema: SuggestTaglinesInputSchema,
    outputSchema: SuggestTaglinesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
